BASELINE_MONTHLY = 13000
BASELINE_MONTHS = 19
BASELINE_ANNUAL = BASELINE_MONTHLY * BASELINE_MONTHS
DEFAULT_TARGET_JOBS = 200
DEFAULT_OUTPUT_FILE = "boss_ranked_jobs.json"
DEFAULT_REPORT_FILE = "boss_ranked_jobs.html"
